[workspace]
members = [
    "quantum_launcher",
    "crates/ql_instances",
    "crates/ql_mod_manager",
    "crates/ql_core",
    "crates/omniarchive_api",
    "crates/ql_servers",
    "crates/ql_plugins",
    "crates/ql_java_handler",
]
resolver = "2"

[workspace.dependencies]
colored = "2"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["fs", "macros", "process"] }
lazy_static = "1"
chrono = "0.4"
zip-extract = "0.2"
thiserror = "2"
rfd = "0.15"

# [profile.dev]
# opt-level = 1

[profile.dev.package."*"]
opt-level = 3
debug = false

[profile.release-dbg]
inherits = "release"
debug = true

[profile.release-ql]
inherits = "release"
opt-level = "s"
# lto = "fat"
strip = "symbols"
