[package]
name = "omniarchive_api"
version = "0.1.0"
edition = "2021"

[dependencies]
ql_core = { path = "../ql_core" }

reqwest = { workspace = true }
colored = { workspace = true }

# HTML Parsing
html5ever = "0.29"
markup5ever_rcdom = "0.3"
