name: Build-RPM

on:
  workflow_dispatch: # allows manual triggering

env:
  BIN_NAME: quantum_launcher
  PROJECT_NAME: quantum_launcher
  REPO_NAME: Mrmayman/quantum-launcher

jobs:
  RPM:
    name: Fedora
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.altarch }}/${{ matrix.os }}:${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker: fedora-latest
            version: latest
            os: fedora
            arch: x86_64
            altarch: amd64

    steps:
      - name: Install Build Dependencies
        run: |
          sudo dnf install rpmdevtools rpmlint @development-tools rpkg git dnf5-plugins --refresh -y

      - name: Clone Repo
        run: |
          git clone https://github.com/Mrmayman/quantumlauncher.git

      - name: Build release package
        run: |
          cd quantumlauncher
          sudo dnf5 builddep -y quantum_launcher.spec
          mkdir ~/rpmlocal && rpkg local --outdir ~/rpmlocal
          rm -f ~/rpmlocal/${{ matrix.arch }}/*debug*

      - name: Build archive
        shell: bash
        run: |
          mkdir dist
          cp ~/rpmlocal/${{ matrix.arch }}/* dist/

      - uses: actions/upload-artifact@v4
        with:
          name: quantum-launcher-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.arch }}
          path: dist
